
const qs=s=>document.querySelector(s), qsa=s=>Array.from(document.querySelectorAll(s)), pct=x=>`${(100*x).toFixed(1)}%`;
let tournament, elo, liveMatches={};
const LS={key:"wk2026.sportsrcKey",endpoint:"wk2026.sportsrcEndpoint",sim:"wk2026.simulations",goal:"wk2026.goalBase",cache:"wk2026.liveCache"};
function status(m){qs("#status").innerHTML=m||""} function fact(n){let r=1;for(let i=2;i<=n;i++)r*=i;return r} function poisson(l,k){return Math.exp(-l)*Math.pow(l,k)/fact(k)}
function name(c){return tournament.teams[c]?.name||c} function rating(c){return elo[c]||tournament.teams[c]?.elo||1600}
function save(){localStorage.setItem(LS.key,qs("#sportsrcKey").value.trim());localStorage.setItem(LS.endpoint,qs("#sportsrcEndpoint").value.trim());localStorage.setItem(LS.sim,qs("#simulations").value);localStorage.setItem(LS.goal,qs("#goalBase").value);status("Instellingen opgeslagen.")}
function loadSettings(){qs("#sportsrcKey").value=localStorage.getItem(LS.key)||"";qs("#sportsrcEndpoint").value=localStorage.getItem(LS.endpoint)||"";qs("#simulations").value=localStorage.getItem(LS.sim)||"5000";qs("#goalBase").value=localStorage.getItem(LS.goal)||"2.6"}
async function loadData(){const [t,e]=await Promise.all([fetch("data/world-cup-2026.json").then(r=>r.json()),fetch("data/elo.json").then(r=>r.json())]);tournament=t;elo=e.ratings||{}}
function norm(s){return String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim()}
function code(v){if(!v)return null;let raw=String(v).trim().toUpperCase();if(tournament.teams[raw])return raw;let n=norm(v);for(const [c,info] of Object.entries(tournament.teams)){if(norm(info.name)===n)return c;if((info.aliases||[]).map(norm).includes(n))return c}return null}
function get(o,paths){for(const p of paths){let cur=o;for(const part of p.split(".")){if(cur==null)break;cur=cur[part]}if(cur!==undefined&&cur!==null&&cur!=="")return cur}return null}
function arrDeep(o){if(Array.isArray(o))return o;if(!o||typeof o!=="object")return [];for(const k of ["data","matches","fixtures","events","response","results"]){if(Array.isArray(o[k]))return o[k]}for(const v of Object.values(o)){let f=arrDeep(v);if(f.length)return f}return []}
function isFinished(s){s=norm(s);return ["finished","final","ft","full time","completed","ended","aet"].some(x=>s.includes(x))}
function isLive(s){s=norm(s);return ["live","in progress","1st half","2nd half","halftime","ht"].some(x=>s.includes(x))}
function normalizeMatch(r){let h=code(get(r,["home.name","homeTeam.name","home_team.name","teams.home.name","competitors.0.name","home","homeTeam"])), a=code(get(r,["away.name","awayTeam.name","away_team.name","teams.away.name","competitors.1.name","away","awayTeam"]));if(!h||!a)return null;let st=get(r,["status","state","matchStatus","fixture.status.short","fixture.status.long"])||"scheduled";let hg=get(r,["score.home","scores.home","goals.home","homeScore","home_score","score.fulltime.home","score.ft.home"]), ag=get(r,["score.away","scores.away","goals.away","awayScore","away_score","score.fulltime.away","score.ft.away"]);return{home:h,away:a,date:get(r,["date","kickoff","startTime","start_time","scheduled","time","fixture.date"]),status:String(st),finished:isFinished(st)||(hg!==null&&ag!==null&&!isLive(st)),live:isLive(st),hg:hg===null?null:Number(hg),ag:ag===null?null:Number(ag),city:get(r,["city","venue.city","stadium.city","location.city"]),venue:get(r,["venue.name","stadium.name","stadium","venue","location.name"])}}
async function loadSportSRC(){let endpoint=qs("#sportsrcEndpoint").value.trim(), key=qs("#sportsrcKey").value.trim();if(!endpoint){liveMatches={};status("Geen SportSRC endpoint: live uitslagen overgeslagen.");return}let c=JSON.parse(localStorage.getItem(LS.cache)||"null"),now=Date.now();if(c&&c.endpoint===endpoint&&now-c.ts<300000){liveMatches=c.matches||{};status(`SportSRC cache gebruikt (${Object.keys(liveMatches).length/2} wedstrijden).`);return}try{let headers={};if(key){headers.Authorization=`Bearer ${key}`;headers["x-api-key"]=key;headers["X-API-Key"]=key}let res=await fetch(endpoint,{headers});if(!res.ok)throw new Error(`HTTP ${res.status}`);let raw=await res.json(), map={};arrDeep(raw).map(normalizeMatch).filter(Boolean).forEach(m=>{map[`${m.home}-${m.away}`]=m;map[`${m.away}-${m.home}`]={...m,home:m.away,away:m.home,hg:m.ag,ag:m.hg}});liveMatches=map;localStorage.setItem(LS.cache,JSON.stringify({ts:now,endpoint,matches:map}));status(`SportSRC geladen: ${Object.keys(map).length/2} wedstrijden herkend.`)}catch(e){liveMatches={};status(`<span class="warn">SportSRC niet geladen: ${e.message}. Fallback op JSON + Elo.</span>`)}}
function live(m){return liveMatches[`${m.home}-${m.away}`]||null}
function dt(x){if(!x)return"";let d=new Date(x);return Number.isNaN(d.getTime())?String(x):d.toLocaleString("nl-NL",{timeZone:"Europe/Amsterdam",dateStyle:"medium",timeStyle:"short"})}
function expGoals(h,a,ko=false){let diff=rating(h)-rating(a), base=Number(qs("#goalBase").value||2.6)+(ko?-0.15:0), adv=Math.max(-1.25,Math.min(1.25,diff/300));return[Math.max(.15,base/2+adv*.55),Math.max(.15,base/2-adv*.55)]}
function matrix(h,a,ko=false){let [eh,ea]=expGoals(h,a,ko),rows=[],tot=0;for(let hg=0;hg<=7;hg++)for(let ag=0;ag<=7;ag++){let p=poisson(eh,hg)*poisson(ea,ag);rows.push({hg,ag,p});tot+=p}rows.forEach(r=>r.p/=tot);return rows.sort((x,y)=>y.p-x.p)}
function likely(h,a,ko=false){return matrix(h,a,ko)[0]} function sample(h,a,ko=false){let rows=matrix(h,a,ko),r=Math.random();for(const row of rows){r-=row.p;if(r<=0)return row}return rows.at(-1)}
function blank(g){return tournament.groups[g].map(team=>({team,group:g,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0}))}
function add(t,h,a,hg,ag){let H=t.find(x=>x.team===h),A=t.find(x=>x.team===a);if(!H||!A)return;H.p++;A.p++;H.gf+=hg;H.ga+=ag;A.gf+=ag;A.ga+=hg;H.gd=H.gf-H.ga;A.gd=A.gf-A.ga;if(hg>ag){H.w++;A.l++;H.pts+=3}else if(hg<ag){A.w++;H.l++;A.pts+=3}else{H.d++;A.d++;H.pts++;A.pts++}}
function cmp(a,b){return(b.pts-a.pts)||(b.gd-a.gd)||(b.gf-a.gf)||(rating(b.team)-rating(a.team))}
function build(mode){let standings={},pred=[];Object.keys(tournament.groups).forEach(g=>standings[g]=blank(g));for(const m of tournament.groupMatches){let p=likely(m.home,m.away),lv=live(m),u={hg:p.hg,ag:p.ag,source:"prediction"};if(mode==="actual"){if(lv?.finished&&lv.hg!==null&&lv.ag!==null)u={hg:lv.hg,ag:lv.ag,source:"actual"};else continue}else if(mode==="projected"&&lv?.finished&&lv.hg!==null&&lv.ag!==null)u={hg:lv.hg,ag:lv.ag,source:"actual"};pred.push({...m,predHg:p.hg,predAg:p.ag,prob:p.p,live:lv,hg:u.hg,ag:u.ag,source:u.source});add(standings[m.group],m.home,m.away,u.hg,u.ag)}Object.keys(standings).forEach(g=>standings[g].sort(cmp));return{standings,predictions:pred}}
function thirds(st){return Object.values(st).map(r=>r[2]).filter(Boolean).sort(cmp).slice(0,8)}
function ref(r,st,w,th,used){if(r.kind==="pos")return st[r.group]?.[r.pos-1]?.team||"TBD";if(r.kind==="winner")return w[r.match]||"TBD";if(r.kind==="third"){let o=th.filter(t=>r.groups.includes(t.group)&&!used.has(t.team)).sort(cmp),ch=o[0]||th.find(t=>!used.has(t.team))||th[0];if(ch)used.add(ch.team);return ch?ch.team:"TBD"}return"TBD"}
function ko(st,stoch=false){let th=thirds(st),used=new Set(),w={},matches=[];for(const m of tournament.knockout){let h=ref(m.home,st,w,th,used),a=ref(m.away,st,w,th,used),s=stoch?sample(h,a,true):likely(h,a,true),win;if(s.hg!==s.ag)win=s.hg>s.ag?h:a;else{let ph=1/(1+Math.pow(10,-(rating(h)-rating(a))/400));win=stoch?(Math.random()<ph?h:a):(ph>=.5?h:a)}w[m.id]=win;matches.push({...m,homeTeam:h,awayTeam:a,hg:s.hg,ag:s.ag,winner:win})}return{matches,winner:w.F1||matches.at(-1)?.winner}}
function sim(projected=true){let st={};Object.keys(tournament.groups).forEach(g=>st[g]=blank(g));for(const m of tournament.groupMatches){let lv=live(m),s=(projected&&lv?.finished&&lv.hg!==null&&lv.ag!==null)?{hg:lv.hg,ag:lv.ag}:sample(m.home,m.away);add(st[m.group],m.home,m.away,s.hg,s.ag)}Object.keys(st).forEach(g=>st[g].sort(cmp));return{standings:st,knockout:ko(st,true)}}
function mc(n,projected=true){let res={};Object.keys(tournament.teams).forEach(t=>res[t]={groupWinner:0,advance:0,qf:0,sf:0,final:0,champion:0});for(let i=0;i<n;i++){let s=sim(projected),th=thirds(s.standings).map(x=>x.team);for(const rows of Object.values(s.standings)){res[rows[0].team].groupWinner++;rows.slice(0,2).forEach(r=>res[r.team].advance++)}th.forEach(t=>res[t].advance++);for(const m of s.knockout.matches){if(m.stage==="Round of 16"){res[m.homeTeam].qf++;res[m.awayTeam].qf++}if(m.stage==="Quarter-final"){res[m.homeTeam].sf++;res[m.awayTeam].sf++}if(m.stage==="Semi-final"){res[m.homeTeam].final++;res[m.awayTeam].final++}}if(s.knockout.winner&&res[s.knockout.winner])res[s.knockout.winner].champion++}Object.values(res).forEach(r=>Object.keys(r).forEach(k=>r[k]/=n));return res}
function table(rows,title){return`<h3>${title}</h3><table><thead><tr><th>Team</th><th class=right>P</th><th class=right>W</th><th class=right>G</th><th class=right>V</th><th class=right>DV</th><th class=right>DT</th><th class=right>DS</th><th class=right>Pnt</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i<2?"✅ ":i===2?"◐ ":""}${name(r.team)}</td><td class=right>${r.p}</td><td class=right>${r.w}</td><td class=right>${r.d}</td><td class=right>${r.l}</td><td class=right>${r.gf}</td><td class=right>${r.ga}</td><td class=right>${r.gd}</td><td class=right><b>${r.pts}</b></td></tr>`).join("")}</tbody></table>`}
function renderSummary(base,proj,kb,kp,mb,mp){let top=Object.entries(mp).sort((a,b)=>b[1].champion-a[1].champion).slice(0,10);qs("#summary").innerHTML=`<div class=grid><div class=card><h2>Baseline winnaar</h2><p class=winner style="font-size:30px">${name(kb.winner)}</p><p class=muted>Vooraf-model zonder echte uitslagen.</p></div><div class=card><h2>Live/projected winnaar</h2><p class=winner style="font-size:30px">${name(kp.winner)}</p><p class=muted>Echte uitslagen + voorspelde rest.</p>${top.map(([t,r])=>`<p>${name(t)} <span class=pill>${pct(r.champion)}</span></p><div class=bar><span style="width:${r.champion*100}%"></span></div>`).join("")}</div></div>`}
function renderGroups(base,actual,proj){let by={};proj.predictions.forEach(m=>(by[m.group]||=[]).push(m));qs("#groups").innerHTML=Object.keys(tournament.groups).map(g=>`<div class=card><h2>Groep ${g}</h2><div class=grid><div>${table(base.standings[g],"Baseline")}</div><div>${table(actual.standings[g],"Werkelijk")}</div><div>${table(proj.standings[g],"Projected")}</div></div><h3>Wedstrijden</h3><table><thead><tr><th>Datum CEST</th><th>Wedstrijd</th><th>Stad</th><th>Stadion</th><th>Status</th><th class=right>Voorspeld</th><th class=right>Werkelijk</th><th class=right>Gebruikt</th></tr></thead><tbody>${(by[g]||[]).map(m=>{let l=m.live,real=l?.finished&&l.hg!==null&&l.ag!==null?`${l.hg}-${l.ag}`:"",used=m.source==="actual"?real:`${m.hg}-${m.ag}`;return`<tr><td>${dt(l?.date||m.date)}</td><td>${name(m.home)} - ${name(m.away)}</td><td>${l?.city||m.city||""}</td><td>${l?.venue||m.venue||""}</td><td>${l?.status||"scheduled"}</td><td class=right>${m.predHg}-${m.predAg}</td><td class=right>${real}</td><td class=right><b>${used}</b> <span class=pill>${m.source}</span></td></tr>`}).join("")}</tbody></table></div>`).join("")}
function renderKo(kb,kp){let stages=["Round of 32","Round of 16","Quarter-final","Semi-final","Final"],r=(k,title)=>`<div class=card><h2>${title}</h2>${stages.map(s=>`<h3>${s}</h3><table><tbody>${k.matches.filter(m=>m.stage===s).map(m=>`<tr><td>${m.id}</td><td>${name(m.homeTeam)} - ${name(m.awayTeam)}</td><td class=right><b>${m.hg}-${m.ag}</b></td><td class=winner>${name(m.winner)}</td></tr>`).join("")}</tbody></table>`).join("")}</div>`;qs("#knockout").innerHTML=`<div class=grid>${r(kb,"Baseline bracket")}${r(kp,"Live/projected bracket")}</div>`}
function renderChances(mb,mp){let rows=Object.keys(tournament.teams).sort((a,b)=>mp[b].champion-mp[a].champion);qs("#chances").innerHTML=`<div class=card><h2>Kampioenskansen</h2><table><thead><tr><th>Team</th><th class=right>Baseline</th><th class=right>Nu</th><th class=right>Door groep nu</th><th class=right>Finale nu</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${name(t)}</td><td class=right>${pct(mb[t].champion)}</td><td class=right><b>${pct(mp[t].champion)}</b></td><td class=right>${pct(mp[t].advance)}</td><td class=right>${pct(mp[t].final)}</td></tr>`).join("")}</tbody></table></div>`}
function renderData(){qs("#data").innerHTML=`<div class=card><h2>Databronnen</h2><p><b>Lokaal:</b> <code>data/world-cup-2026.json</code> en <code>data/elo.json</code>.</p><p><b>SportSRC:</b> optioneel. Vul endpoint en key in. Ontbrekende velden worden overgeslagen.</p><p><b>Cache:</b> 5 minuten in <code>localStorage</code>.</p></div>`}
async function run(){try{save();if(!tournament)await loadData();await loadSportSRC();let n=Math.max(100,Math.min(50000,Number(qs("#simulations").value||5000))),base=build("baseline"),actual=build("actual"),proj=build("projected"),kb=ko(base.standings),kp=ko(proj.standings);let old=liveMatches;liveMatches={};let mb=mc(n,false);liveMatches=old;let mp=mc(n,true);renderSummary(base,proj,kb,kp,mb,mp);renderGroups(base,actual,proj);renderKo(kb,kp);renderChances(mb,mp);renderData()}catch(e){qs("#summary").innerHTML=`<div class=error><b>Fout:</b> ${e.message}</div>`}}
function init(){qsa(".tab").forEach(b=>b.addEventListener("click",()=>{qsa(".tab,.tabPanel").forEach(x=>x.classList.remove("active"));b.classList.add("active");qs("#"+b.dataset.tab).classList.add("active")}));loadSettings();qs("#saveBtn").onclick=save;qs("#runBtn").onclick=run;qs("#clearBtn").onclick=()=>{localStorage.removeItem(LS.cache);status("Cache gewist.")};run()}
init();
