
const SPORTDB_UPSTREAM="https://api.sportdb.dev/api/flashscore/football";
const POLY_URL="https://gamma-api.polymarket.com/markets";
const qs=s=>document.querySelector(s), qsa=s=>Array.from(document.querySelectorAll(s));
const pct=x=>x===undefined||x===null||Number.isNaN(x)?"N/A":`${(100*x).toFixed(1)}%`;
const setVal=(s,v)=>{const e=qs(s); if(e)e.value=v};
const getVal=(s,d="")=>{const e=qs(s); return e?e.value:d};
let tournament, elo, liveMatches={}, polyMarkets=[], polyTeamPrices={}, polyMatchMarkets={}, isRunning=false;
const LS={proxy:"v9.sportdbProxy",poly:"v9.polyQuery",polyMode:"v9.polyMode",score:"v9.scoreMode",seed:"v9.seed",sim:"v9.simulations",goal:"v9.goalBase",sportCache:"v9.sportCache",polyCache:"v9.polyCache"};

function status(m){qs("#status").innerHTML=m||""}
function saveSettings(){localStorage.setItem(LS.proxy,getVal("#sportdbProxy").trim());localStorage.setItem(LS.poly,getVal("#polyQuery").trim());localStorage.setItem(LS.polyMode,getVal("#polyMode","search"));localStorage.setItem(LS.score,getVal("#scoreMode","likely"));localStorage.setItem(LS.seed,getVal("#variantSeed","2026"));localStorage.setItem(LS.sim,getVal("#simulations","1000"));localStorage.setItem(LS.goal,getVal("#goalBase","2.7"))}
function loadSettings(){setVal("#sportdbProxy",localStorage.getItem(LS.proxy)||"");setVal("#polyQuery",localStorage.getItem(LS.poly)||"world cup 2026 winner");setVal("#polyMode",localStorage.getItem(LS.polyMode)||"search");setVal("#scoreMode",localStorage.getItem(LS.score)||"likely");setVal("#variantSeed",localStorage.getItem(LS.seed)||"2026");setVal("#simulations",localStorage.getItem(LS.sim)||"1000");setVal("#goalBase",localStorage.getItem(LS.goal)||"2.7")}
async function loadData(){const [t,e]=await Promise.all([fetch("data/world-cup-2026.json").then(r=>r.json()),fetch("data/elo.json").then(r=>r.json())]);tournament=t;elo=e.ratings||{}}
const fact=n=>{let r=1;for(let i=2;i<=n;i++)r*=i;return r}; const poisson=(l,k)=>Math.exp(-l)*Math.pow(l,k)/fact(k);
const name=c=>tournament.teams[c]?.name||c; const rating=c=>elo[c]||tournament.teams[c]?.elo||1600;
function norm(s){return String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim()}
function code(v){if(!v)return null;let raw=String(v).trim().toUpperCase();if(tournament.teams[raw])return raw;let n=norm(v);for(const[c,info]of Object.entries(tournament.teams)){if(norm(info.name)===n)return c;if((info.aliases||[]).map(norm).includes(n))return c}return null}
function get(o,paths){for(const p of paths){let cur=o;for(const part of p.split(".")){if(cur==null)break;cur=cur[part]}if(cur!==undefined&&cur!==null&&cur!=="")return cur}return null}
function arrDeep(o){if(Array.isArray(o))return o;if(!o||typeof o!=="object")return[];for(const k of["data","matches","fixtures","events","response","results","games"]){if(Array.isArray(o[k]))return o[k]}for(const v of Object.values(o)){let f=arrDeep(v);if(f.length)return f}return[]}
function isFinished(s){s=norm(s);return["finished","final","ft","full time","completed","ended","aet"].some(x=>s.includes(x))}
function isLive(s){s=norm(s);return["live","in progress","1st half","2nd half","halftime","ht"].some(x=>s.includes(x))}
function normalizeMatch(r){let h=code(get(r,["home.name","homeTeam.name","home_team.name","teams.home.name","participants.home.name","competitors.0.name","home","homeTeam"])),a=code(get(r,["away.name","awayTeam.name","away_team.name","teams.away.name","participants.away.name","competitors.1.name","away","awayTeam"]));if(!h||!a)return null;let st=get(r,["status","state","matchStatus","status.name","fixture.status.short","fixture.status.long"])||"scheduled",hg=get(r,["score.home","scores.home","goals.home","homeScore","home_score","score.fulltime.home","score.ft.home","scores.fulltime.home","home.score"]),ag=get(r,["score.away","scores.away","goals.away","awayScore","away_score","score.fulltime.away","score.ft.away","scores.fulltime.away","away.score"]);return{home:h,away:a,date:get(r,["date","kickoff","startTime","start_time","scheduled","time","fixture.date","startTimestamp"]),status:String(st),finished:isFinished(st)||(hg!==null&&ag!==null&&!isLive(st)),live:isLive(st),hg:hg===null?null:Number(hg),ag:ag===null?null:Number(ag),city:get(r,["city","venue.city","stadium.city","location.city"]),venue:get(r,["venue.name","stadium.name","stadium","venue","location.name"])}}
async function loadSportDB(){liveMatches={};let proxy=getVal("#sportdbProxy").trim();if(!proxy){status("Geen SportDB proxy: live uitslagen overgeslagen.");return}let c=JSON.parse(localStorage.getItem(LS.sportCache)||"null"),now=Date.now();if(c&&c.proxy===proxy&&now-c.ts<300000){liveMatches=c.matches||{};status(`SportDB cache gebruikt (${Object.keys(liveMatches).length/2} wedstrijden).`);return}try{let res=await fetch(proxy);if(!res.ok)throw new Error(`HTTP ${res.status}`);let raw=await res.json(),map={};arrDeep(raw).map(normalizeMatch).filter(Boolean).forEach(m=>{map[`${m.home}-${m.away}`]=m;map[`${m.away}-${m.home}`]={...m,home:m.away,away:m.home,hg:m.ag,ag:m.hg}});liveMatches=map;localStorage.setItem(LS.sportCache,JSON.stringify({ts:now,proxy,matches:map}));status(`SportDB via proxy geladen: ${Object.keys(map).length/2} wedstrijden herkend.`)}catch(e){status(`<span class=warn>SportDB niet geladen: ${e.message}. Fallback op JSON + Elo.</span>`)}}
function parseJsonMaybe(v){if(Array.isArray(v))return v;if(typeof v==="string"){try{return JSON.parse(v)}catch(e){return[]}}return[]}
function priceNum(v){let n=Number(v);return Number.isFinite(n)?n:null}
function marketText(m){return `${m.question||m.title||""} ${m.slug||""}`.toLowerCase()}
function hasTeamInMarket(m,t){const txt=marketText(m),info=tournament.teams[t]||{},names=[info.name,...(info.aliases||[]),t].map(norm).filter(Boolean);return names.some(n=>txt.includes(n))}
function findMatchMarket(home,away){const m=polyMarkets.find(x=>hasTeamInMarket(x,home)&&hasTeamInMarket(x,away));if(!m)return null;const outs=parseJsonMaybe(m.outcomes),prices=parseJsonMaybe(m.outcomePrices||m.outcome_prices),out={};outs.forEach((o,i)=>{const c=code(o),p=priceNum(prices[i]);if(c&&p!==null)out[c]=p;if(["draw","tie","gelijk"].some(w=>norm(o).includes(w))&&p!==null)out.DRAW=p});return{market:m,prices:out}}
async function fetchPolyMarkets(mode,q){if(!q)return[];let url=mode==="slug"?`${POLY_URL}?closed=false&limit=10&slug=${encodeURIComponent(q)}`:`${POLY_URL}?closed=false&limit=100&search=${encodeURIComponent(q)}`;let res=await fetch(url);if(!res.ok)throw new Error(`HTTP ${res.status}`);let d=await res.json();if(!Array.isArray(d))d=d.data||[];if(mode==="slug"){const exact=d.filter(m=>m.slug===q);return exact.length?exact:d}return d}
async function loadPolymarket(){polyMarkets=[];polyTeamPrices={};polyMatchMarkets={};let q=getVal("#polyQuery").trim(),mode=getVal("#polyMode","search");if(!q)return;let c=JSON.parse(localStorage.getItem(LS.polyCache)||"null"),now=Date.now();if(c&&c.q===q&&c.mode===mode&&now-c.ts<300000){polyMarkets=c.markets||[];polyTeamPrices=c.prices||{};polyMatchMarkets=c.matchMarkets||{};return}try{polyMarkets=(await fetchPolyMarkets(mode,q)).slice(0,50);let prices={};for(const m of polyMarkets){let outs=parseJsonMaybe(m.outcomes),ps=parseJsonMaybe(m.outcomePrices||m.outcome_prices);outs.forEach((o,i)=>{let c=code(o),p=priceNum(ps[i]);if(c&&p!==null)prices[c]=Math.max(prices[c]||0,p)})}polyTeamPrices=prices;for(const gm of tournament.groupMatches){let found=findMatchMarket(gm.home,gm.away);if(found)polyMatchMarkets[gm.id]={question:found.market.question||found.market.title||"",slug:found.market.slug||"",home:found.prices[gm.home],draw:found.prices.DRAW,away:found.prices[gm.away]}}localStorage.setItem(LS.polyCache,JSON.stringify({ts:now,q,mode,markets:polyMarkets,prices:polyTeamPrices,matchMarkets:polyMatchMarkets}))}catch(e){polyMarkets=[];polyTeamPrices={};polyMatchMarkets={}}}
function live(m){return liveMatches[`${m.home}-${m.away}`]||null}
function dt(x,mode="full"){if(!x)return"";if(typeof x==="number"&&x<9999999999)x*=1000;let d=new Date(x);if(Number.isNaN(d.getTime()))return String(x);return mode==="day"?d.toLocaleDateString("nl-NL",{timeZone:"Europe/Amsterdam",weekday:"long",day:"numeric",month:"long",year:"numeric"}):d.toLocaleString("nl-NL",{timeZone:"Europe/Amsterdam",dateStyle:"medium",timeStyle:"short"})}
function timeOnly(x){let d=new Date(x);return Number.isNaN(d.getTime())?"":d.toLocaleTimeString("nl-NL",{timeZone:"Europe/Amsterdam",hour:"2-digit",minute:"2-digit"})}
function expGoals(h,a,ko=false){let diff=rating(h)-rating(a),base=Number(getVal("#goalBase","2.7"))+(ko?-0.15:0),adv=Math.max(-1.25,Math.min(1.25,diff/300));return[Math.max(.15,base/2+adv*.55),Math.max(.15,base/2-adv*.55)]}
function matrix(h,a,ko=false){let[xh,xa]=expGoals(h,a,ko),rows=[],tot=0;for(let hg=0;hg<=7;hg++)for(let ag=0;ag<=7;ag++){let p=poisson(xh,hg)*poisson(xa,ag);rows.push({hg,ag,p});tot+=p}rows.forEach(r=>r.p/=tot);return rows.sort((a,b)=>b.p-a.p)}
const likely=(h,a,ko=false)=>matrix(h,a,ko)[0];
function hashString(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function seededRandom(seed){let t=seed>>>0;return()=>{t+=0x6D2B79F5;let r=Math.imul(t^t>>>15,1|t);r^=r+Math.imul(r^r>>>7,61|r);return((r^r>>>14)>>>0)/4294967296}}
function sample(h,a,ko=false,seedKey=""){let rows=matrix(h,a,ko),rnd=seedKey?seededRandom(hashString(seedKey)):Math.random,r=seedKey?rnd():Math.random();for(const row of rows){r-=row.p;if(r<=0)return row}return rows.at(-1)}
function displayScore(h,a,id,ko=false){let mode=getVal("#scoreMode","likely");if(mode==="rounded"){let[xh,xa]=expGoals(h,a,ko);return{hg:Math.round(xh),ag:Math.round(xa),p:null,mode}}if(mode==="variant")return{...sample(h,a,ko,`${getVal("#variantSeed","2026")}-${id}-${h}-${a}`),mode};return{...likely(h,a,ko),mode}}
function outcome(h,a){let rows=matrix(h,a),homeWin=0,draw=0,awayWin=0;rows.forEach(r=>{if(r.hg>r.ag)homeWin+=r.p;else if(r.hg<r.ag)awayWin+=r.p;else draw+=r.p});let[xh,xa]=expGoals(h,a);return{homeWin,draw,awayWin,xh,xa}}
function blank(g){return tournament.groups[g].map(team=>({team,group:g,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0}))}
function add(t,h,a,hg,ag){let H=t.find(x=>x.team===h),A=t.find(x=>x.team===a);if(!H||!A)return;H.p++;A.p++;H.gf+=hg;H.ga+=ag;A.gf+=ag;A.ga+=hg;H.gd=H.gf-H.ga;A.gd=A.gf-A.ga;if(hg>ag){H.w++;A.l++;H.pts+=3}else if(hg<ag){A.w++;H.l++;A.pts+=3}else{H.d++;A.d++;H.pts++;A.pts++}}
const cmp=(a,b)=>(b.pts-a.pts)||(b.gd-a.gd)||(b.gf-a.gf)||(rating(b.team)-rating(a.team));
function build(mode){let standings={},pred=[];Object.keys(tournament.groups).forEach(g=>standings[g]=blank(g));for(const m of tournament.groupMatches){let score=displayScore(m.home,m.away,m.id),lv=live(m),used={hg:score.hg,ag:score.ag,source:"prediction"};if(mode==="actual"){if(lv?.finished&&lv.hg!==null&&lv.ag!==null)used={hg:lv.hg,ag:lv.ag,source:"actual"};else continue}else if(mode==="projected"&&lv?.finished&&lv.hg!==null&&lv.ag!==null)used={hg:lv.hg,ag:lv.ag,source:"actual"};pred.push({...m,score,odds:outcome(m.home,m.away),live:lv,hg:used.hg,ag:used.ag,source:used.source});add(standings[m.group],m.home,m.away,used.hg,used.ag)}Object.keys(standings).forEach(g=>standings[g].sort(cmp));return{standings,predictions:pred}}
function thirds(st){return Object.values(st).map(r=>r[2]).filter(Boolean).sort(cmp).slice(0,8)}
function ref(r,st,w,th,used){if(r.kind==="pos")return st[r.group]?.[r.pos-1]?.team||"TBD";if(r.kind==="winner")return w[r.match]||"TBD";if(r.kind==="third"){let o=th.filter(t=>r.groups.includes(t.group)&&!used.has(t.team)).sort(cmp),ch=o[0]||th.find(t=>!used.has(t.team))||th[0];if(ch)used.add(ch.team);return ch?ch.team:"TBD"}return"TBD"}
function ko(st,stoch=false){let th=thirds(st),used=new Set(),w={},matches=[];for(const m of tournament.knockout){let h=ref(m.home,st,w,th,used),a=ref(m.away,st,w,th,used),s=stoch?sample(h,a,true):displayScore(h,a,m.id,true),win;if(s.hg!==s.ag)win=s.hg>s.ag?h:a;else{let ph=1/(1+Math.pow(10,-(rating(h)-rating(a))/400));win=stoch?(Math.random()<ph?h:a):(ph>=.5?h:a)}w[m.id]=win;matches.push({...m,homeTeam:h,awayTeam:a,hg:s.hg,ag:s.ag,winner:win})}return{matches,winner:w.F1||matches.at(-1)?.winner}}
function simulate(projected=true){let st={};Object.keys(tournament.groups).forEach(g=>st[g]=blank(g));for(const m of tournament.groupMatches){let lv=live(m),s=(projected&&lv?.finished&&lv.hg!==null&&lv.ag!==null)?{hg:lv.hg,ag:lv.ag}:sample(m.home,m.away);add(st[m.group],m.home,m.away,s.hg,s.ag)}Object.keys(st).forEach(g=>st[g].sort(cmp));return{standings:st,knockout:ko(st,true)}}
function mc(n,projected=true){let res={};Object.keys(tournament.teams).forEach(t=>res[t]={groupWinner:0,advance:0,qf:0,sf:0,final:0,champion:0});for(let i=0;i<n;i++){let s=simulate(projected),th=thirds(s.standings).map(x=>x.team);for(const rows of Object.values(s.standings)){res[rows[0].team].groupWinner++;rows.slice(0,2).forEach(r=>res[r.team].advance++)}th.forEach(t=>res[t].advance++);for(const m of s.knockout.matches){if(m.stage==="Round of 16"){res[m.homeTeam].qf++;res[m.awayTeam].qf++}if(m.stage==="Quarter-final"){res[m.homeTeam].sf++;res[m.awayTeam].sf++}if(m.stage==="Semi-final"){res[m.homeTeam].final++;res[m.awayTeam].final++}}if(res[s.knockout.winner])res[s.knockout.winner].champion++}Object.values(res).forEach(r=>Object.keys(r).forEach(k=>r[k]/=n));return res}
function standingsTable(rows,title){return`<h3>${title}</h3><table><thead><tr><th>Team</th><th class=right>P</th><th class=right>W</th><th class=right>G</th><th class=right>V</th><th class=right>DV</th><th class=right>DT</th><th class=right>DS</th><th class=right>Pnt</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i<2?"✅ ":i===2?"◐ ":""}${name(r.team)}</td><td class=right>${r.p}</td><td class=right>${r.w}</td><td class=right>${r.d}</td><td class=right>${r.l}</td><td class=right>${r.gf}</td><td class=right>${r.ga}</td><td class=right>${r.gd}</td><td class=right><b>${r.pts}</b></td></tr>`).join("")}</tbody></table>`}
function matchRow(m){let l=m.live,real=l?.finished&&l.hg!==null&&l.ag!==null?`${l.hg}-${l.ag}`:"N/A",used=m.source==="actual"?real:`${m.hg}-${m.ag}`,pm=polyMatchMarkets[m.id],pmText=pm?`${name(m.home)} ${pct(pm.home)} / X ${pct(pm.draw)} / ${name(m.away)} ${pct(pm.away)}`:"N/A";return`<tr><td>${timeOnly(l?.date||m.date)}</td><td>${m.group}</td><td>${name(m.home)} - ${name(m.away)}</td><td>${l?.city||m.city||""}</td><td>${l?.venue||m.venue||""}</td><td>${l?.status||"scheduled"}</td><td class=right>${m.odds.xh.toFixed(1)}-${m.odds.xa.toFixed(1)}</td><td class=right>${pct(m.odds.homeWin)} / ${pct(m.odds.draw)} / ${pct(m.odds.awayWin)}</td><td class=right>${m.score.hg}-${m.score.ag}</td><td class=right>${real}</td><td class=right><b>${used}</b></td><td>${pmText}</td></tr>`}
function matchCard(m){let l=m.live,real=l?.finished&&l.hg!==null&&l.ag!==null?`${l.hg}-${l.ag}`:"N/A",used=m.source==="actual"?real:`${m.hg}-${m.ag}`,pm=polyMatchMarkets[m.id],pmText=pm?`${pct(pm.home)} / ${pct(pm.draw)} / ${pct(pm.away)}`:"N/A";return`<div class=matchCard><div class=matchCardTop><span class=pill>Groep ${m.group}</span><span>${dt(l?.date||m.date)}</span></div><h3>${name(m.home)} - ${name(m.away)}</h3><div class=matchMeta>${l?.city||m.city||""}${(l?.city||m.city)&&(l?.venue||m.venue)?" · ":""}${l?.venue||m.venue||""}</div><div class=matchGrid><div><span>xG</span><b>${m.odds.xh.toFixed(1)}-${m.odds.xa.toFixed(1)}</b></div><div><span>1/X/2</span><b>${pct(m.odds.homeWin)} / ${pct(m.odds.draw)} / ${pct(m.odds.awayWin)}</b></div><div><span>Score</span><b>${m.score.hg}-${m.score.ag}</b></div><div><span>Werkelijk</span><b>${real}</b></div><div><span>Gebruikt</span><b>${used}</b></div><div><span>Polymarket</span><b>${pmText}</b></div></div></div>`}
function renderMatchdays(proj){let matches=[...proj.predictions].sort((a,b)=>new Date(a.live?.date||a.date)-new Date(b.live?.date||b.date)),days={};matches.forEach(m=>(days[dt(m.live?.date||m.date,"day")]||=[]).push(m));qs("#matchdays").innerHTML=Object.entries(days).map(([day,ms])=>`<div class=card><h2>${day}</h2><div class=desktopTable><table><thead><tr><th>Tijd</th><th>Groep</th><th>Wedstrijd</th><th>Stad</th><th>Stadion</th><th>Status</th><th class=right>xG</th><th class=right>1/X/2</th><th class=right>Score</th><th class=right>Werkelijk</th><th class=right>Gebruikt</th><th>Polymarket</th></tr></thead><tbody>${ms.map(matchRow).join("")}</tbody></table></div><div class=matchCards>${ms.map(matchCard).join("")}</div></div>`).join("")}
function renderGroups(base,actual,proj){qs("#groups").innerHTML=Object.keys(tournament.groups).map(g=>`<div class=card><h2>Groep ${g}</h2><div class=grid><div>${standingsTable(base.standings[g],"Baseline")}</div><div>${standingsTable(actual.standings[g],"Werkelijk")}</div><div>${standingsTable(proj.standings[g],"Projected")}</div></div></div>`).join("")}
function renderKnockout(kb,kp){let stages=["Round of 32","Round of 16","Quarter-final","Semi-final","Final"],r=(k,t)=>`<div class=card><h2>${t}</h2>${stages.map(s=>`<h3>${s}</h3><table><tbody>${k.matches.filter(m=>m.stage===s).map(m=>`<tr><td>${m.id}</td><td>${name(m.homeTeam)} - ${name(m.awayTeam)}</td><td class=right><b>${m.hg}-${m.ag}</b></td><td class=winner>${name(m.winner)}</td></tr>`).join("")}</tbody></table>`).join("")}</div>`;qs("#knockout").innerHTML=`<div class=grid>${r(kb,"Baseline bracket")}${r(kp,"Live/projected bracket")}</div>`}
function renderChances(mb,mp){let rows=Object.keys(tournament.teams).sort((a,b)=>(polyTeamPrices[b]??-1)-(polyTeamPrices[a]??-1)||mp[b].champion-mp[a].champion);qs("#chances").innerHTML=`<div class=card><h2>Kampioenskansen</h2><table><thead><tr><th>Team</th><th class=right>Baseline</th><th class=right>Nu</th><th class=right>Polymarket</th><th class=right>PM - Nu</th><th class=right>Finale nu</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${name(t)}</td><td class=right>${pct(mb[t].champion)}</td><td class=right><b>${pct(mp[t].champion)}</b></td><td class=right>${pct(polyTeamPrices[t])}</td><td class=right>${polyTeamPrices[t]==null?"N/A":((polyTeamPrices[t]-mp[t].champion)>=0?"+":"")+pct(polyTeamPrices[t]-mp[t].champion)}</td><td class=right>${pct(mp[t].final)}</td></tr>`).join("")}</tbody></table></div>`}
function renderMarkets(){let matchRows=tournament.groupMatches.map(m=>{let pm=polyMatchMarkets[m.id];return`<tr><td>${m.group}</td><td>${name(m.home)} - ${name(m.away)}</td><td>${pm?"✅ gevonden":"N/A"}</td><td class=right>${pm?pct(pm.home):"N/A"}</td><td class=right>${pm?pct(pm.draw):"N/A"}</td><td class=right>${pm?pct(pm.away):"N/A"}</td><td>${pm?.question||""}</td></tr>`}).join("");qs("#markets").innerHTML=`<div class=card><h2>Polymarket</h2><p class=muted>Modus: <code>${getVal("#polyMode","search")}</code> · Query/slug: <code>${getVal("#polyQuery","")}</code></p><h3>Wedstrijdmarkten</h3><table><thead><tr><th>Groep</th><th>Wedstrijd</th><th>Status</th><th class=right>Home</th><th class=right>Draw</th><th class=right>Away</th><th>Market</th></tr></thead><tbody>${matchRows}</tbody></table><h3>Teamprijzen</h3><table><tbody>${Object.keys(tournament.teams).sort((a,b)=>(polyTeamPrices[b]??-1)-(polyTeamPrices[a]??-1)).map(t=>`<tr><td>${name(t)}</td><td class=right><b>${pct(polyTeamPrices[t])}</b></td></tr>`).join("")}</tbody></table><h3>Gevonden markten</h3><table><tbody>${polyMarkets.map(m=>`<tr><td>${m.question||m.title||""}</td><td>${m.slug||""}</td></tr>`).join("")||"<tr><td>Geen markten gevonden.</td></tr>"}</tbody></table></div>`}
function renderAbout(){qs("#about").innerHTML=`<div class=card><h2>Model</h2><p>Teamsterkte komt uit Elo. Elo-verschil wordt vertaald naar expected goals. Daarna gebruikt de app een Poisson-verdeling voor scorekansen en Monte Carlo voor toernooikansen.</p><p><b>Scoremodus</b>: meest waarschijnlijk toont de score met de hoogste losse kans; afgeronde xG rondt de verwachting af; realistische variant samplet een score met vaste seed.</p><p><b>SportDB</b>: live uitslagen werken via je Cloudflare Worker proxy. Zonder proxy blijft de app werken met lokale JSON + Elo.</p></div>`}
async function run(){if(isRunning)return;isRunning=true;let btn=qs("#runBtn");btn.disabled=true;btn.textContent="Bezig...";try{saveSettings();if(!tournament)await loadData();await loadSportDB();await loadPolymarket();let n=Math.max(100,Math.min(50000,Number(getVal("#simulations","1000")))),base=build("baseline"),actual=build("actual"),proj=build("projected"),kb=ko(base.standings),kp=ko(proj.standings);let old=liveMatches;liveMatches={};let mb=mc(n,false);liveMatches=old;let mp=mc(n,true);renderMatchdays(proj);renderGroups(base,actual,proj);renderKnockout(kb,kp);renderChances(mb,mp);renderMarkets();renderAbout();status(`Klaar. Simulaties: ${n}. Scoremodus: ${getVal("#scoreMode","likely")}.`)}catch(e){status(`<span class=warn>Fout: ${e.message}</span>`)}finally{isRunning=false;btn.disabled=false;btn.textContent="Genereer"}}
function init(){loadSettings();qsa(".tab").forEach(b=>b.onclick=()=>{qsa(".tab,.tabPanel").forEach(x=>x.classList.remove("active"));b.classList.add("active");qs("#"+b.dataset.tab).classList.add("active")});qs("#runBtn").onclick=run;qs("#clearBtn").onclick=()=>{localStorage.removeItem(LS.sportCache);localStorage.removeItem(LS.polyCache);status("Cache gewist.")};renderAbout()}
init();
